In [70]:
import pandas as pd

In [71]:
df = pd.read_csv(r"D:\learning\Laptop\laptops_dataset_final_600.csv")

In [72]:
df.sample(10)

,product_name,overall_rating,no_ratings,no_reviews,rating,title,review
4681,CHUWI Intel Core i5 10th Gen 1035G1 - (16 GB/512 GB SSD/Window...,4.1,636,106,5,Great product,I'm Satisfied... Smooth Operator.\nValu for money
18840,HP 15s Intel Core i5 13th Gen 1334U - (16 GB/512 GB SSD/Window...,4.2,390,33,5,Perfect product!,Superb.. Booting time is 10-12 seconds. Very smooth Laptop. Must Buy..
12248,HP Victus Intel Core i5 12th Gen 12450H - (8 GB/512 GB SSD/Win...,4.4,"2,388",124,5,Just wow!,Good
4117,HP 255 G9 AMD Ryzen 3 Dual Core R3 3250 - (8 GB/512 GB SSD/Win...,4.0,685,48,4,Wonderful,Good quality
3812,Acer Aspire 3 Intel Core i3 12th Gen 1215U - (8 GB/512 GB SSD/...,4.2,"2,786",221,5,Terrific purchase,Good
6890,ZEBRONICS Pro Series Z Intel Core i5 12th Gen 1235U - (8 GB/51...,3.9,866,119,4,Delightful,"Nice product , 😃"
8910,ASUS Vivobook 15 Intel Core i3 12th Gen 1215U - (8 GB/512 GB S...,4.3,"9,156",698,5,Just wow!,Super
8748,ASUS ROG Ally AMD Ryzen Z1 Octa Core Extreme - (16 GB/512 GB S...,4.4,732,118,5,Excellent,Excellent product but the battery backup can be improved
3029,ASUS Vivobook 15 Intel Core i5 12th Gen 1235U - (8 GB/512 GB S...,4.2,"5,789",310,5,Did not meet expectations,BETTERY PERFORMANCE VERY VERY BAD
18599,Lenovo IdeaPad Gaming 3 AMD Ryzen 5 Quad Core 5500H - (8 GB/51...,4.2,306,28,3,Just okay,I am writing this review after 1 month of use\nThere are some pros and cons in it\nBut it is value for money in 45k\n\nCons:\n1. Battery consumption it lasts only for 1 hour in gaming and in normal usage 2 hours maximum.\n2. Low volume it's volume speakers sound is lower than my phone volume literally without headphones you hear properly.\n3. In photo and in question area they said it has RGB lights but in real it has only white backlit keyboard\n\nPros:\n1. In every question and answer area ppl s...\nREAD MORE

In [73]:
df.describe(include="all")

,product_name,overall_rating,no_ratings,no_reviews,rating,title,review
count,24113,24113.000000,24113,24113,24113.000000,24113,24113
unique,365,NaN,288,147,NaN,213,11223
top,Apple MacBook AIR Apple M2 - (8 GB/256 GB SSD/Mac OS Monterey)...,NaN,"5,789",310,NaN,Wonderful,Good
freq,400,NaN,600,600,NaN,1266,753
mean,NaN,4.186273,NaN,NaN,4.214573,NaN,NaN
std,NaN,0.228392,NaN,NaN,1.184845,NaN,NaN
min,NaN,3.300000,NaN,NaN,1.000000,NaN,NaN
25%,NaN,4.100000,NaN,NaN,4.000000,NaN,NaN
50%,NaN,4.200000,NaN,NaN,5.000000,NaN,NaN
75%,NaN,4.300000,NaN,NaN,5.000000,NaN,NaN
max,NaN,5.000000,NaN,NaN,5.000000,NaN,NaN

#### Business Features

In [131]:
# Create a Column for categorize Sentiment Poor (0–2), Average (2–3), Good (3–4), and Excellent (4–5).
labels=['Poor', 'Average', 'Good', 'Excellent']
df["rating_category"] = pd.cut(df["rating"],bins = [0,2,3,4,5], labels=labels )
df

,product_name,overall_rating,no_ratings,no_reviews,rating,title,review,rating_category,brand,ram_gb,storage_gb,is_gaming,gpu,battery_mentioned,performance_mentioned,display_mentioned,heating_issue
0,Apple MacBook AIR Apple M2 - (8 GB/256 GB SSD/Mac OS Monterey)...,4.7,"15,210",900,5,Perfect product!,"Loved it, it's my first MacBook that I earned from my hardwork 🥺❤️",Excellent,Apple,8,256,NO,Integrated,False,False,False,False
1,Apple MacBook AIR Apple M2 - (8 GB/256 GB SSD/Mac OS Monterey)...,4.7,"15,210",900,5,Fabulous!,Battery lasted longer than my first relationship (2 days).\nListening to Arijit singh songs on full volume since then still isn't getting over. Has more warmth than her. unlike her there's two way communication here as touchpad is very responsive. fingerprint lock is nice as it only opens up to me. 5 stars for this -1 for her,Excellent,Apple,8,256,NO,Integrated,True,False,False,False
2,Apple MacBook AIR Apple M2 - (8 GB/256 GB SSD/Mac OS Monterey)...,4.7,"15,210",900,5,Fabulous!,Such a great deal.. very happy with the performance and battery life..Origional product..🥰❤️\nThank you Flipkart..!!!,Excellent,Apple,8,256,NO,Integrated,True,True,False,False
3,Apple MacBook AIR Apple M2 - (8 GB/256 GB SSD/Mac OS Monterey)...,4.7,"15,210",900,4,Delightful,"Awesome build quality and very good display, battery and camera. Still new to macOS",Good,Apple,8,256,NO,Integrated,True,False,True,False
4,Apple MacBook AIR Apple M2 - (8 GB/256 GB SSD/Mac OS Monterey)...,4.7,"15,210",900,5,Awesome,"When i ordered and came to know about seller review,i was scared that in what condition i will get macbook. but i was wrong.\n\nThis is my first macbook and i am fully satisfied with the product with original packaging of apple and got genuine product.\n\nIt's very thin and light and looks very premium.\n\nAs A software developer, i installed intellij idea ide and guess what.\nIt's magic,it is opening just in a click and within 5 seconds.\nGreat performance, no heating issue, sound quality awesome an...\nREAD MORE",Excellent,Apple,8,256,NO,Integrated,False,True,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24108,MSI Modern 14 Intel Core i5 13th Gen 1335U - (8 GB/512 GB SSD/...,4.3,156,24,5,Perfect product!,"MSI Laptop is high performance and the best. configuration is better than HP,Dell .\nValue for money laptop\n\nCon\nBattery backup is up to 5 hours",Excellent,MSI,8,512,NO,Integrated,True,True,False,False
24109,MSI Modern 14 Intel Core i5 13th Gen 1335U - (8 GB/512 GB SSD/...,4.3,156,24,5,Perfect product!,Excellent performance best laptop.,Excellent,MSI,8,512,NO,Integrated,False,True,False,False
24110,MSI Modern 14 Intel Core i5 13th Gen 1335U - (8 GB/512 GB SSD/...,4.3,156,24,4,"Good product, Lacks features.","Decent battery life. Exceptional build quality. Lacks features like USB-C charger, privacy shutter for camera, fingerprint reader, MS Office.",Good,MSI,8,512,NO,Integrated,True,False,False,False
24111,Lenovo IdeaPad 5 2-in-1 WUXGA IPS AMD Ryzen 7 Octa Core 8845HS...,4.4,7,2,3,Nice,The product does not support facial recognition as it does not have an IR sensor,Average,Lenovo,NaN,NaN,NO,Integrated,False,False,False,False
24112,Lenovo IdeaPad 5 2-in-1 WUXGA IPS AMD Ryzen 7 Octa Core 8845HS...,4.4,7,2,4,Very Good,DISPLAY IS A LET DOWN. But the lenovo Pen works like a CHARM. I haven't yet tested it with powerful apps but i believe AMD Ryzen 7 can handle it. This is the CHEAPEST LAPTOP with AMD 8845H I guess,Good,Lenovo,NaN,NaN,NO,Integrated,False,False,True,False

## Extracting

#### Extracting Brand Name

In [126]:
# Extract the brand_Name


brands = ['Apple','ASUS','Lenovo','HP','Acer','MSI','Dell']
def extract_brand(product):
    for brand in brands:
        if brand.lower() in product.lower():
            return brand
    return 'Other'

df['brand'] = df['product_name'].apply(extract_brand)

#### Extracting Hardware Specs

In [123]:
#Extract Hardware Specs

#RAM 
df['ram_gb'] = df['product_name'].str.extract(r'(\d+)\s*GB')

#Storage
df['storage_gb'] = df['product_name'].str.extract(r'/(\d+)\s*GB SSD')


#Extract GPU

def extract_gpu(text):

    text = str(text)

    if 'RTX 4050' in text:
        return 'RTX 4050'

    elif 'RTX 4060' in text:
        return 'RTX 4060'

    elif 'RTX 3050' in text:
        return 'RTX 3050'

    elif 'RTX 2050' in text:
        return 'RTX 2050'

    else:
        return 'Integrated'

df['gpu'] = df['product_name'].apply(extract_gpu)

#### Extracting High Value Features

In [119]:
#Battery Mention 


#If you want to check whether a column contains a string, use .str.contains():
battery_keywords = [
    'battery',
    'backup',
    'charge',
    'charging',
    'drain'
]

df['battery_mentioned'] = (
    df['review']
    .str.lower()
    .str.contains('battery|backup|charge|charging|drain', na=False)  # use '|'.join(battery_keywords) instead 'battery|backup|charge|charging|drain'
)

In [120]:
# Performance Mention
performance_keywords = [
    'performance',
    'fast',
    'speed',
    'smooth',
    'gaming',
    'lag'
]
df['performance_mentioned'] = (
    df['review']
    .str.lower()
    .str.contains('|'.join(performance_keywords), na=False)
)

In [121]:
# Display Mention
display_keywords = [
    'display',
    'screen',
    'brightness'
]

df['display_mentioned'] = (
    df['review']
    .str.lower()
    .str.contains('|'.join(display_keywords), na=False)
)

In [122]:
#Heating Issue
heating_keywords = [
    'heat',
    'heating',
    'hot',
    'thermal'
]

df['heating_issue'] = (
    df['review']
    .str.lower()
    .str.contains('|'.join(heating_keywords), na=False)
)

## IDENTIFY GAMING LAPTOP

In [127]:
#Identify Gaming Laptops
gaming_keywords = [
    'gaming',
    'tuf',
    'rog',
    'nitro',
    'victus',
    'legion',
    'loq'
]

def gaming(product):
    for game in gaming_keywords:
        if game.lower() in product.lower():
            return game
    return "NO" 

df['is_gaming'] = df['product_name'].apply(gaming)

## Validate Column

In [128]:
#Validate
df.columns.to_list

<bound method IndexOpsMixin.tolist of Index(['product_name', 'overall_rating', 'no_ratings', 'no_reviews', 'rating',
       'title', 'review', 'rating_category', 'brand', 'ram_gb', 'storage_gb',
       'is_gaming', 'gpu', 'battery_mentioned', 'performance_mentioned',
       'display_mentioned', 'heating_issue'],
      dtype='str')>

## Identify Missing Values

In [115]:
df.isna().sum()

product_name                 0
overall_rating               0
no_ratings                   0
no_reviews                   0
rating                       0
title                        0
review                       0
rating_category              0
brand                        0
ram_gb                    2340
storage_gb               14029
is_gaming                    0
gpu                          0
battery_mentioned            0
performance_mentioned        0
display_mentioned            0
dtype: int64

#### Tackle the Missing Value

In [116]:
# Identifying the Naming convention of the Product, because of the Missing value
df[df["ram_gb"].isna()]["product_name"].head(10)
# the dataset creator already truncated the product names before saving the CSV.

473    SAMSUNG Galaxy Book4 Metal Intel Core i3 13th Gen 1315U - (8 G...
474    SAMSUNG Galaxy Book4 Metal Intel Core i3 13th Gen 1315U - (8 G...
475    SAMSUNG Galaxy Book4 Metal Intel Core i3 13th Gen 1315U - (8 G...
476    SAMSUNG Galaxy Book4 Metal Intel Core i3 13th Gen 1315U - (8 G...
477    SAMSUNG Galaxy Book4 Metal Intel Core i3 13th Gen 1315U - (8 G...
478    SAMSUNG Galaxy Book4 Metal Intel Core i3 13th Gen 1315U - (8 G...
479    SAMSUNG Galaxy Book4 Metal Intel Core i3 13th Gen 1315U - (8 G...
480    SAMSUNG Galaxy Book4 Metal Intel Core i3 13th Gen 1315U - (8 G...
481    SAMSUNG Galaxy Book4 Metal Intel Core i3 13th Gen 1315U - (8 G...
482    SAMSUNG Galaxy Book4 Metal Intel Core i3 13th Gen 1315U - (8 G...
Name: product_name, dtype: str

In [132]:
display(df['ram_gb'].value_counts(dropna=False))
display(df['storage_gb'].value_counts(dropna=False))

ram_gb
8      12451
16      7108
NaN     2340
4       1862
12       172
24       167
32        13
Name: count, dtype: int64

storage_gb
NaN    14029
512     8937
256     1013
128      134
Name: count, dtype: int64

## Export DF as CSV

In [136]:
df.to_csv("Laptop_cleaned.csv", index=False)